apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: resource-usage-analysis
spec:
  metrics:
    - name: pod-count
      successCondition: "result[0] >= 3"
      failureCondition: "result[0] < 3"
      provider:
        prometheus:
          address: http://prometheus-operated.default.svc.cluster.local:9090
          query: |
            count(kube_pod_info{namespace="default", pod=~"example-app-.*"})
